# Generated by Django 5.2.3 on 2025-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='release_date',
            field=models.DateField(verbose_name='дата выхода на рынок'),
        ),
    ]
