# Generated by Django 5.2.3 on 2025-07-03 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0002_alter_counterparties_email_alter_counterparties_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnerships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.ImageField(blank=True, default=0, null=True, upload_to='', verbose_name='Задолженность поставщику')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='person', to='counterparties.counterparties', verbose_name='Контрагент')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='supplier2', to='partnerships.partnerships', verbose_name='Контрагент')),
            ],
        ),
    ]
