# Generated by Django 5.2.3 on 2025-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0001_initial'),
        ('products', '0002_alter_products_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerships',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.products', verbose_name='Список продуктов'),
        ),
    ]
