# Generated by Django 5.2.3 on 2025-07-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partnerships", "0002_partnerships_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerships",
            name="debt",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Задолженность поставщику",
            ),
        ),
    ]
