# Generated by Django 5.2.3 on 2025-07-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0005_alter_partnerships_products'),
        ('products', '0002_alter_products_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerships',
            name='products',
            field=models.ManyToManyField(help_text='ID продукта: 1, 2 , 6', related_name='products', to='products.products', verbose_name='Список продуктов'),
        ),
    ]
