# Generated by Django 5.2.3 on 2025-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparties',
            name='email',
            field=models.CharField(max_length=150, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='counterparties',
            name='name',
            field=models.CharField(help_text='Название контрагента', max_length=50, verbose_name='Название контрагента'),
        ),
    ]
